dmenu-library script

diff --git a/.local/bin/scripts/cheatsheet b/.local/bin/scripts/cheatsheet
--- a/.local/bin/scripts/cheatsheet
+++ b/.local/bin/scripts/cheatsheet
@@ -1,17 +1,30 @@
 #!/bin/bash
 
 # Search in the cheatsheet folder
-# usage: cheatsheet [file] search-term
 
-cheatsheet_folder="/home/adrian/Notes/Lists/Cheatsheets/"
+cheatsheet_folder="/home/adrian/Notes/Lists/Cheatsheets"
 
-if [ "$#" -le 1 ]; then                                 # If no options are given, search in the general file
-    grep -i "$1" "$cheatsheet_folder/general.md"
-else                                                    # If file is given, seach in file.md
-    if [ ! -f "$cheatsheet_folder/$1.md" ]; then            # If file does not exists, send error
-        echo -n "Invalid file. Available files: " >&2
-        ls $cheatsheet_folder >&2
-        exit 1
-    fi
-    grep -i "$2" "$cheatsheet_folder/$1.md"
+#----------------
+#   CLI version
+#----------------
+## usage: cheatsheet [file] search-term
+#
+#if [ "$#" -le 1 ]; then                                 # If no options are given, search in the general file
+    #grep -i "$1" "$cheatsheet_folder/general.md"
+#else                                                    # If file is given, seach in file.md
+    #if [ ! -f "$cheatsheet_folder/$1.md" ]; then            # If file does not exists, send error
+        #echo -n "Invalid file. Available files: " >&2
+        #ls $cheatsheet_folder >&2
+        #exit 1
+    #fi
+    #grep -i "$2" "$cheatsheet_folder/$1.md"
+#fi
+
+#----------------
+# dmenu version
+#----------------
+cheatsheet_file=$(ls "$cheatsheet_folder" | sed 's/\.[^.]*$//' | dmenu -l 20 -p "Cheatsheet:").md
+
+if [ -f "$cheatsheet_folder/$cheatsheet_file" ]; then
+    terminal-init "cd \"$cheatsheet_folder\"; nvim $cheatsheet_file"
 fi
